import {
    TextNode,
    NodeKey,
    EditorConfig,
    LexicalNode,
    SerializedTextNode
} from 'lexical';

/**
 * AIGeneratedNode Custom Lexical Node
 * Represents text that has been actively generated by the LLM inference service.
 * Applies specific styling and prepares the DOM for accept/reject keystroke handlers.
 */
export class AIGeneratedNode extends TextNode {
    /**
     * Identifies the node type internally within the Lexical engine.
     */
    static getType(): string {
        return 'ai-generated';
    }

    /**
     * Clones the node to maintain immutability in the Lexical state tree.
     */
    static clone(node: AIGeneratedNode): AIGeneratedNode {
        return new AIGeneratedNode(node.__text, node.__key);
    }

    constructor(text: string, key?: NodeKey) {
        super(text, key);
    }

    /**
     * Mounts the node to the DOM and applies the theme class mapped in theme.ts.
     */
    createDOM(config: EditorConfig): HTMLElement {
        const dom = super.createDOM(config);
        const className = config.theme.aiGenerated;
        if (className !== undefined) {
            dom.className = className;
        }
        // Identifies the element for event listeners targeting AI text interactions
        dom.setAttribute('data-ai-generated', 'true');
        return dom;
    }

    /**
     * Determines if the DOM needs to be re-rendered during a state update.
     * We return false here unless the underlying text content changes, to prevent layout thrashing.
     */
    updateDOM(prevNode: AIGeneratedNode, dom: HTMLElement, config: EditorConfig): boolean {
        const isUpdated = super.updateDOM(prevNode, dom, config);
        return isUpdated;
    }

    static importJSON(serializedNode: SerializedTextNode): AIGeneratedNode {
        const node = $createAIGeneratedNode(serializedNode.text);
        node.setFormat(serializedNode.format);
        node.setDetail(serializedNode.detail);
        node.setMode(serializedNode.mode);
        node.setStyle(serializedNode.style);
        return node;
    }

    exportJSON(): SerializedTextNode {
        return {
            ...super.exportJSON(),
            type: 'ai-generated',
        };
    }
}

/**
 * Factory function to safely create a new instance of AIGeneratedNode within Lexical context.
 */
export function $createAIGeneratedNode(text: string): AIGeneratedNode {
    return new AIGeneratedNode(text);
}

/**
 * Type guard to check if an arbitrary LexicalNode is an AIGeneratedNode.
 */
export function $isAIGeneratedNode(node: LexicalNode | null | undefined): node is AIGeneratedNode {
    return node instanceof AIGeneratedNode;
}